In [1]:
# import numpy

import numpy as np


In [3]:
# print 1 dimentional array

arr= np.array([1,2,3])
print(arr)

[1 2 3]


In [4]:
# print an array fill with zero 

print(np.zeros([3,3]))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
# print an array fill with ones 

print(np.ones([3,3]))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [6]:
# print an array fill with any number like 5 

print(np.full([3,3],5))

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [7]:
# print an array that show even no b/w 1 to 50

print(np.arange(0,50,2))

[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48]


In [9]:
# print an array find 10 no. b/w 1 to 3 

print(np.linspace(0,3,10))

[0.         0.33333333 0.66666667 1.         1.33333333 1.66666667
 2.         2.33333333 2.66666667 3.        ]


In [10]:
# print dignol matrix 

print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [11]:
# print dignol matrix and we decide its dignol values

print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [14]:
# rint an array those vales convert into float tye

np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [16]:
# rint an array those vales convert into int tye

arr=np.array([1.8,2.6,9.9])
print(arr.astype(int))

[1 2 9]
